site_name: The Coverage Space
site_description: A place to track your code coverage metrics.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/coverage-space
google_analytics: ['UA-6468614-12', 'coverage.space']

theme: mkdocs

pages:
- Home: 'index.md'
- About:
  - 'Release Notes': 'about/changes.md'
  - Contributing: 'about/contributing.md'
  - License: 'about/license.md'
