[pytest]

addopts =
    -ra
    --last-failed
    --cov=api
    --cov-report=html
    --cov-report=term-missing:skip-covered
    --no-cov-on-fail

filterwarnings =
    ignore:.*:DeprecationWarning:flask_api
    ignore:.*:DeprecationWarning:werkzeug.urls
    ignore:.*:DeprecationWarning:werkzeug.wsgi

cache_dir = .cache
